export const productConfig = {
  name: "Antarctic Fish Krill Oil",
  banglaName: "অ্যান্টার্কটিক ফিশ ক্রিল অয়েল",
  form: "Softgel Capsules",
  capsulesPerBottle: 60,
  capsulesLabel: "প্রতি বোতলে ৬০টি সফটজেল ক্যাপসুল",
  badges: [
    { icon: "💊", label: "60 Capsules", sub: "প্রতি বোতলে" },
    { icon: "👑", label: "Premium Formula", sub: "প্রিমিয়াম মান" },
    { icon: "🚚", label: "Free Delivery", sub: "ফ্রি ডেলিভারি" },
  ],
  bullets: [
    "Omega 3 Support",
    "Daily Wellness Support",
    "Premium Antarctic Source",
    "60 Softgel Capsules",
  ],
  spec: [
    "60 Softgel Capsules",
    "DHA & EPA Support",
    "Premium Antarctic Source",
    "Easy-to-take Formula",
  ],
  heroImages: [
    "/images/hero-bottle-1.jpg",
    "/images/hero-bottle-2.jpg",
    "/images/hero-bottle-3.jpg",
    "/images/bottle-with-capsules.jpg",
    "/images/bottle-luxury-1.jpg",
  ],
  bottleImages: [
    "/images/hero-bottle-1.jpg",
    "/images/hero-bottle-2.jpg",
    "/images/hero-bottle-3.jpg",
    "/images/bottle-luxury-1.jpg",
    "/images/bottle-trio.jpg",
  ],
  capsuleImages: [
    "/images/capsule-1.jpg",
    "/images/capsule-2.jpg",
    "/images/capsule-3.jpg",
    "/images/bottle-with-capsules.jpg",
    "/images/capsule-1.jpg",
  ],
  lifestyleImages: [
    "/images/lifestyle-1.jpg",
    "/images/lifestyle-2.jpg",
    "/images/lifestyle-3.jpg",
    "/images/lifestyle-4.jpg",
    "/images/lifestyle-1.jpg",
  ],
  showcaseImages1: [
    "/images/hero-bottle-1.jpg",
    "/images/hero-bottle-2.jpg",
    "/images/bottle-luxury-1.jpg",
    "/images/bottle-trio.jpg",
    "/images/hero-bottle-3.jpg",
    "/images/bottle-with-capsules.jpg",
    "/images/capsule-1.jpg",
  ],
  showcaseImages2: [
    "/images/capsule-1.jpg",
    "/images/capsule-2.jpg",
    "/images/capsule-3.jpg",
    "/images/bottle-with-capsules.jpg",
    "/images/capsule-1.jpg",
    "/images/capsule-2.jpg",
    "/images/antarctic-source.jpg",
  ],
  showcaseImages3: [
    "/images/lifestyle-1.jpg",
    "/images/lifestyle-2.jpg",
    "/images/lifestyle-4.jpg",
    "/images/lifestyle-3.jpg",
    "/images/lifestyle-1.jpg",
    "/images/lifestyle-2.jpg",
    "/images/lifestyle-4.jpg",
  ],
};